services:
  nginx:
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/image.png:/tmp/minicat.png
      - ./nginx/ssl.crt:/etc/nginx/ssl.crt
      - ./nginx/ssl.key:/etc/nginx/ssl.key
      - ./nginx/file.txt:/tmp/file.txt

  bubuntu:
    image: ubuntu:20.04
    command: sleep infinity

